name: Health check

on:
  schedule:
    - chron: '* * * * *'
    
jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Ping url
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://rough-snowflake-3938.fly.dev/